server:
  port: 8080

#配置数据源
spring:
  datasource:                                    #需要配置时区，否则报错
    url: jdbc:mysql://localhost:3306/jpa-0909-001?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #开启jpa
  jpa:      #把jpa的sql打印出来
    show-sql: true
    hibernate:    #通过hibernate来实现
      ddl-auto: update

#create：每次启动都会建表，数据清理
#create-drop：每次加载hibernate时根据model类生成表，但sessionFactory已关闭，表就自动销毁了
#update：第一次加载 hibernate 时根据 model 类会自动建立起表的结 构（前提是先建立好数据库），以后加载 hibernate 时根据 model 类自动更新表结构
#validate：每次加载 hibernate 时，验证创建数据库表结构，只会和数据库中的表进行 比较，不会创建新表，但是会插入新值。